import ast
import json
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import tomllib
import unittest


ROOT = Path(__file__).parents[1]
PLUGIN = ROOT / "plugins/codexmax-orchestrator"
COMMANDS = {
    "orcastrata-assignment": "codexmax-assignment",
    "orcastrata-orchestrate": "codexmax-orchestrate",
    "orcastrata-discover": "codexmax-discover",
    "orcastrata-plan": "codexmax-plan",
    "orcastrata-route": "codexmax-route",
    "orcastrata-supervise": "codexmax-supervise",
    "orcastrata-audit": "codexmax-verify",
    "orcastrata-audit-full": "codexmax-audit-full",
    "orcastrata-closeout": "codexmax-closeout",
    "orcastrata-config": "codexmax-config",
    "orcastrata-loop": "codexmax-loop",
}


class OrcastrataNativeInterfaceTests(unittest.TestCase):
    def test_commands_are_thin_aliases_to_existing_skills(self):
        paths = sorted((PLUGIN / "commands").glob("*.toml"))
        self.assertEqual(sorted(path.stem for path in paths), sorted(COMMANDS))
        for path in paths:
            command = tomllib.loads(path.read_text(encoding="utf-8"))
            prompt = command["prompt"]
            tokens = [word for word in prompt.split() if word.startswith("$codexmax-orchestrator:")]
            self.assertEqual(tokens, [f"$codexmax-orchestrator:{COMMANDS[path.stem]}"])
            self.assertIn("{{args}}", prompt)
            self.assertTrue((PLUGIN / "skills" / COMMANDS[path.stem] / "SKILL.md").is_file())

    def test_audit_full_is_advisory_and_read_only(self):
        focused = (PLUGIN / "commands/orcastrata-audit.toml").read_text(encoding="utf-8")
        full = (PLUGIN / "skills/codexmax-audit-full/SKILL.md").read_text(encoding="utf-8")
        self.assertIn("codexmax-verify", focused)
        for verdict in ("`ACCEPT`", "`REVISE`", "`BLOCKED`"):
            self.assertIn(verdict, full)
        for boundary in ("read-only", "Only the Parent can accept", "Never repair"):
            self.assertIn(boundary, full)

    def test_manifest_wires_the_native_hook(self):
        manifest = json.loads((PLUGIN / ".codex-plugin/plugin.json").read_text(encoding="utf-8"))
        self.assertEqual(manifest["hooks"], "./hooks/hooks.json")
        hooks = json.loads((PLUGIN / "hooks/hooks.json").read_text(encoding="utf-8"))["hooks"]
        self.assertEqual(set(hooks), {"SessionStart", "SubagentStart"})
        self.assertTrue(all("$PLUGIN_ROOT/hooks/orcastrata_context.py" in item["hooks"][0]["command"] for rows in hooks.values() for item in rows))

    def test_hook_is_bounded_event_specific_and_stdlib_only(self):
        script = PLUGIN / "hooks/orcastrata_context.py"
        imports = {
            alias.name.split(".")[0]
            for node in ast.walk(ast.parse(script.read_text(encoding="utf-8")))
            if isinstance(node, ast.Import)
            for alias in node.names
        }
        self.assertEqual(imports, {"json", "sys"})
        for event in ("SessionStart", "SubagentStart"):
            run = subprocess.run(
                [sys.executable, str(script)],
                input=json.dumps({"hook_event_name": event}),
                text=True,
                capture_output=True,
                check=True,
            )
            output = json.loads(run.stdout)
            specific = output["hookSpecificOutput"]
            self.assertEqual(specific["hookEventName"], event)
            self.assertLessEqual(len(run.stdout.encode("utf-8")), 512)
        malformed = subprocess.run(
            [sys.executable, str(script)], input="not-json", text=True,
            capture_output=True, check=True,
        )
        self.assertEqual(json.loads(malformed.stdout), {})

    def test_cache_parity_ignores_only_pycache_bytecode(self):
        with tempfile.TemporaryDirectory() as temporary:
            cache = Path(temporary) / "codexmax-orchestrator/1.2.0"
            shutil.copytree(PLUGIN, cache)
            generated = cache / "scripts/__pycache__/generated.cpython-313.pyc"
            generated.parent.mkdir(exist_ok=True)
            generated.write_bytes(b"generated bytecode")
            command = [
                sys.executable,
                str(PLUGIN / "scripts/verify_release_parity.py"),
                "verify",
                "--source-root",
                str(PLUGIN),
                "--cache-root",
                str(cache),
            ]
            passing = subprocess.run(command, text=True, capture_output=True)
            self.assertEqual(passing.returncode, 0, passing.stdout)

            (cache / "standalone.pyc").write_bytes(b"unexpected bytecode")
            rejected = subprocess.run(command, text=True, capture_output=True)
            self.assertEqual(rejected.returncode, 2)
            self.assertEqual(json.loads(rejected.stdout)["failure"], "cache_file_extra")


if __name__ == "__main__":
    unittest.main()
